-- ============================================================================
-- Paslanmaz Takip — Supabase şeması (çok kiracılı / multi-tenant)
-- Bu dosyanın TAMAMINI Supabase Dashboard > SQL Editor'e yapıştırıp Run deyin.
-- Ayrıntılı kurulum adımları: KURULUM.md
-- ============================================================================

create extension if not exists pgcrypto;

-- ============ KİRACILIK (şirketler ve üyelikler) ============

create table public.orgs (
  id uuid primary key default gen_random_uuid(),
  ad text not null,
  created_at timestamptz not null default now()
);

create table public.org_members (
  org_id uuid not null references public.orgs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rol text not null check (rol in ('owner', 'member')),
  email text not null,
  created_at timestamptz not null default now(),
  primary key (org_id, user_id),
  unique (user_id) -- bir kullanıcı yalnız bir şirkete üye olabilir
);

-- Platform davet kodları: yeni şirket ancak bu kodlardan biriyle kurulabilir.
create table public.invite_codes (
  code text primary key,
  note text not null default '',
  created_at timestamptz not null default now(),
  used_by uuid references auth.users(id),
  used_at timestamptz,
  org_id uuid references public.orgs(id)
);

-- Şirket katılım kodları: sahip üretir, mesai arkadaşı bu kodla aynı şirkete katılır.
create table public.org_join_codes (
  code text primary key,
  org_id uuid not null references public.orgs(id) on delete cascade,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  used_by uuid references auth.users(id),
  used_at timestamptz
);

-- ============ YARDIMCI FONKSİYONLAR ============

create or replace function public.current_org_id()
returns uuid language sql stable security definer set search_path = public as $$
  select org_id from org_members where user_id = auth.uid() limit 1
$$;

create or replace function public.is_platform_admin()
returns boolean language sql stable as $$
  select coalesce(lower(auth.jwt()->>'email') = 'timurhan.duzgun.20@hotmail.com', false)
$$;

create or replace function public.rastgele_kod()
returns text language sql volatile as $$
  select upper(encode(gen_random_bytes(4), 'hex'))
$$;

-- ============ ALAN TABLOLARI ============
-- org_id her tabloda default current_org_id(): istemci insert'lerinin org_id
-- göndermesi gerekmez; RLS WITH CHECK yine de doğrular.

create table public.products (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade
    default public.current_org_id(),
  kart_kodu text not null,
  aciklama text not null default '',
  grup text not null default '',
  standart text not null default '',
  standart_adi text not null default '',
  bas_tipi text not null default '',
  olcu double precision,
  boy_mm double precision,
  boyut_metni text not null default '',
  kalite text not null default '',
  dis_tipi text not null default '',
  kaynak text not null default 'manuel',
  in_catalog boolean not null default true,
  unique (org_id, kart_kodu)
);
create index products_org_grup on public.products (org_id, grup);
create index products_org_kaynak on public.products (org_id, kaynak);

create table public.customers (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade
    default public.current_org_id(),
  ad text not null,
  telefon text not null default '',
  email text not null default ''
);
create index customers_org_ad on public.customers (org_id, ad);

create table public.suppliers (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade
    default public.current_org_id(),
  ad text not null,
  telefon text not null default '',
  email text not null default ''
);
create index suppliers_org_ad on public.suppliers (org_id, ad);

create table public.demands (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade
    default public.current_org_id(),
  tarih text not null, -- 'YYYY-MM-DD'
  customer_id bigint not null, -- kasıtlı olarak FK yok: müşteri silinse de talep yaşar
  product_id bigint,           -- kasıtlı olarak FK yok
  serbest_metin text not null default '',
  grup text not null default '',
  standart text not null default '',
  olcu double precision,
  boy_mm double precision,
  kalite text not null default '',
  durum text not null default 'BEKLEMEDE' check (durum in ('BEKLEMEDE', 'VERILDI', 'VERILMEDI')),
  kayip_nedeni text not null default '',
  created_at bigint not null -- epoch ms
);
create index demands_org_created on public.demands (org_id, created_at desc);
create index demands_org_tarih on public.demands (org_id, tarih);

create table public.order_lists (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade
    default public.current_org_id(),
  ad text not null,
  created_at bigint not null
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.orgs(id) on delete cascade
    default public.current_org_id(),
  liste_id bigint not null references public.order_lists(id) on delete cascade,
  product_id bigint,
  aciklama text not null default '',
  grup text not null default '',
  standart text not null default '',
  adet integer not null default 1
);
create index order_items_org_liste on public.order_items (org_id, liste_id);

-- ============ SATIR GÜVENLİĞİ (RLS) ============

alter table public.orgs enable row level security;
alter table public.org_members enable row level security;
alter table public.invite_codes enable row level security;
alter table public.org_join_codes enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.suppliers enable row level security;
alter table public.demands enable row level security;
alter table public.order_lists enable row level security;
alter table public.order_items enable row level security;

create policy org_all on public.products for all to authenticated
  using (org_id = public.current_org_id())
  with check (org_id = public.current_org_id());
create policy org_all on public.customers for all to authenticated
  using (org_id = public.current_org_id())
  with check (org_id = public.current_org_id());
create policy org_all on public.suppliers for all to authenticated
  using (org_id = public.current_org_id())
  with check (org_id = public.current_org_id());
create policy org_all on public.demands for all to authenticated
  using (org_id = public.current_org_id())
  with check (org_id = public.current_org_id());
create policy org_all on public.order_lists for all to authenticated
  using (org_id = public.current_org_id())
  with check (org_id = public.current_org_id());
create policy org_all on public.order_items for all to authenticated
  using (org_id = public.current_org_id())
  with check (org_id = public.current_org_id());

create policy org_read on public.orgs for select to authenticated
  using (id = public.current_org_id());
create policy members_read on public.org_members for select to authenticated
  using (org_id = public.current_org_id());
-- orgs / org_members / kod tablolarına yazma politikası YOK:
-- tüm yazımlar aşağıdaki SECURITY DEFINER fonksiyonlar üzerinden yapılır.
create policy admin_codes on public.invite_codes for select to authenticated
  using (public.is_platform_admin());
create policy owner_join_codes on public.org_join_codes for select to authenticated
  using (org_id = public.current_org_id());

-- ============ RPC FONKSİYONLARI ============

-- Yeni şirket kur: davet kodunu doğrula + yak, org + owner üyeliği oluştur.
create or replace function public.kurulus_olustur(davet_kodu text, sirket_adi text)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_org uuid;
  v_code text;
begin
  if auth.uid() is null then raise exception 'GIRIS_GEREKLI'; end if;
  if exists (select 1 from org_members where user_id = auth.uid()) then
    raise exception 'ZATEN_UYE';
  end if;
  if coalesce(trim(sirket_adi), '') = '' then raise exception 'SIRKET_ADI_BOS'; end if;

  update invite_codes set used_by = auth.uid(), used_at = now()
    where code = upper(trim(davet_kodu)) and used_by is null
    returning code into v_code;
  if v_code is null then raise exception 'KOD_GECERSIZ'; end if;

  insert into orgs (ad) values (trim(sirket_adi)) returning id into v_org;
  update invite_codes set org_id = v_org where code = v_code;
  insert into org_members (org_id, user_id, rol, email)
    values (v_org, auth.uid(), 'owner', coalesce(auth.jwt()->>'email', ''));
  return v_org;
end $$;

-- Katılım koduyla mevcut şirkete üye ol.
create or replace function public.kurulusa_katil(katilim_kodu text)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_org uuid;
begin
  if auth.uid() is null then raise exception 'GIRIS_GEREKLI'; end if;
  if exists (select 1 from org_members where user_id = auth.uid()) then
    raise exception 'ZATEN_UYE';
  end if;
  update org_join_codes set used_by = auth.uid(), used_at = now()
    where code = upper(trim(katilim_kodu)) and used_by is null
    returning org_id into v_org;
  if v_org is null then raise exception 'KOD_GECERSIZ'; end if;
  insert into org_members (org_id, user_id, rol, email)
    values (v_org, auth.uid(), 'member', coalesce(auth.jwt()->>'email', ''));
  return v_org;
end $$;

-- Şirket sahibi, mesai arkadaşı için tek kullanımlık katılım kodu üretir.
create or replace function public.katilim_kodu_olustur()
returns text language plpgsql security definer set search_path = public as $$
declare
  v_kod text;
begin
  if not exists (select 1 from org_members where user_id = auth.uid() and rol = 'owner') then
    raise exception 'SADECE_SAHIP';
  end if;
  v_kod := public.rastgele_kod();
  insert into org_join_codes (code, org_id, created_by)
    values (v_kod, public.current_org_id(), auth.uid());
  return v_kod;
end $$;

-- Platform yöneticisi (satış için) toplu davet kodu üretir.
create or replace function public.davet_kodu_olustur(adet integer, aciklama text default '')
returns setof text language plpgsql security definer set search_path = public as $$
declare
  i int;
  v text;
begin
  if not public.is_platform_admin() then raise exception 'YETKISIZ'; end if;
  for i in 1..least(coalesce(adet, 1), 50) loop
    v := public.rastgele_kod();
    insert into invite_codes (code, note) values (v, coalesce(aciklama, ''));
    return next v;
  end loop;
end $$;

-- Oturum açan kullanıcının üyelik bilgisi (AuthContext bootstrap okuması).
create or replace function public.uyeligim()
returns table (org_id uuid, rol text, org_ad text)
language sql stable security definer set search_path = public as $$
  select m.org_id, m.rol, o.ad
  from org_members m join orgs o on o.id = m.org_id
  where m.user_id = auth.uid()
$$;

-- ============ BAŞLANGIÇ ============
-- İlk şirketin (platform sahibinin kendi şirketi) kurulabilmesi için bilinen kod:
insert into invite_codes (code, note) values ('KURUCU2026', 'ilk kurulum');
